### PR TITLE
fix `empty!` bug

### LINKED ISSUE #26: empty!(lru) when using finalizer sets maxsize to 0
Because of: https://github.com/JuliaCollections/LRUCache.jl/blob/0bc1a491e216ffe7979575516cc279587182ca4a/src/LRUCache.jl#L221

### PR DESCRIPTION
**Pull request by ericphanson**
Easy fix for https://github.com/JuliaCollections/LRUCache.jl/issues/26. The test I added fails on master.

(closes #26)

### CODE REVIEW

**Comment by ericphanson** [comment]
why is appveyor running, there's no workflow/config here? it has your name on it @ararslan, perhaps you can remove it from within appveyor itself?

**Comment by Jutho** [comment]
I vaguely remember looking into AppVeyor and not being able to disable it. Thanks for your PRs. They look great.

**Comment by ararslan** [comment]
Wild, I have no memory of setting up AppVeyor here to run on my account. Anyway, I deleted it from AppVeyor.

**Review by ararslan — APPROVED** [review]

**Comment by ericphanson** [comment]
Alex kindly invited me to JuliaCollections, so I will do some minor cleanup of the issues etc.

**Pull request merged**
