### PR TITLE
new interface with deprecations for old interface

### PR DESCRIPTION
**Pull request by Jutho**
work in progress:
first commit changes source, tests use old interface to test deprecation
second commit updates README to new interface (and adds a slight change to the interface, see below)
third commit updates tests and benchmark
fourth commit adds project.toml and new version tag.

### CODE REVIEW

**Comment by Jutho** [comment]
Unlike mentioned in https://github.com/JuliaCollections/LRUCache.jl/issues/12, I did decide to keep `Base.resize!` as the name for changing `maxsize`, because in the end this function still has the (potential) effect of resizing the structure. However, you don't specify the length but the `maxsize`, which is why I still changed this to be a required keyword argument.

**Comment by Jutho** [comment]
When CI is done, I think this PR is ready to be merged, but maybe an external review is nice, e.g. @jcrist  or @simonbyrne ?

However, to tag a new version, can I just assume JuliaRegistrator is enabled and working for this repository. I cannot set it up I think. Do I need to become a member of JuliaCollections for that. Or can somebody else do this?

**Comment by Jutho** [comment]
The CI failure on mac only is probably due to the fact that I forgot to capitalize project.toml, which matters on mac as the file system is case sensitive. However, git(hub?) does not recognize simply capitalizing the name of that file as a change that can be committed, so I'll have to do two commits: remove and add.

**Comment by Jutho** [comment]
This fixed CI. This PR now looks ready to me.

**Comment by jcrist** [comment]
> However, to tag a new version, can I just assume JuliaRegistrator is enabled and working for this repository. I cannot set it up I think. Do I need to become a member of JuliaCollections for that. Or can somebody else do this?

JuliaRegistrator is new to me, I'm not sure what that is (I haven't written Julia code in 4+ years). You are an admin on this repo though, so should have permission to do whatever you need to do.

**Review by jcrist — APPROVED** [review]
LGTM

**Comment by jcrist** [comment]
At this point I fully cede this repo to you - you are far more suited than myself at this point to determine if changes to this library are valid and necessary than I am. Please feel free to make whatever changes you deem valid without consulting me.

**Comment by Jutho** [comment]
Thanks for your trust, and for creating this nice package in the first place. I'll go ahead and merge this.

**Pull request merged**
